apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-stillingshistorikk
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  secureLogs:
    enabled: true
  vault:
    enabled: false
  webproxy: false
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  kafka:
    pool: {{ kafka_pool }}
  accessPolicy:
    inbound:
      rules:
        - application: pam-ad-api
        - application: pam-ad
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: {{ azure_ad_tenant }}
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  filesFrom:
    - secret: pam-stillingshistorikk-credentials
      mountPath: /var/run/secrets/credentials/pam-stillingshistorikk
  env:
    - name: ADLISTENER_GROUP_ID
      value: "{{ adlistener_group_id }}"
    - name: ADLISTENER_TOPIC
      value: "{{ adlistener_topic }}"
    - name: ADLISTENER_ENABLED
      value: "{{ adlistener_enabled }}"
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/run/secrets/credentials/pam-stillingshistorikk/secret"
    - name: GOOGLE_CLOUD_PROJECT
      value: "{{ google_cloud_project }}"
    - name: GOOGLE_BIGQUERY_DATASET
      value: "{{ google_bigquery_dataset }}"